name: Build and Deploy NestJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Run NestJS Server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            
            # Pull the latest changes
            git reset --hard && git clean -fd && git pull origin main

            npm i
            
            npx pm2 restart byahe-api || npx pm2 start npm --name 'byahe-api' -- npm run start:prod
            
            npx pm2 save